### ISSUE TITLE
Python 3 installation don't work with the easygui module

### ISSUE THREAD

**Issue by hamdyaea** [deadhead420/anarchy-linux#547]
I installed Python 3 from the installer then installed pygame and easygui for my python software.

I try to launch my python program then I have this error :

Traceback (most recent call last):
File "multiquestions-scrum-quiz.py", line 26, in
game_start = buttonbox(title=start_title,image=logo,msg=start_msg,choices=play)
File "/usr/lib/python3.6/site-packages/easygui/boxes/button_box.py", line 102, in buttonbox
callback=callback)
File "/usr/lib/python3.6/site-packages/easygui/boxes/button_box.py", line 147, in init
self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
File "/usr/lib/python3.6/site-packages/easygui/boxes/button_box.py", line 263, in init
self.boxRoot = tk.Tk()
File "/usr/lib/python3.6/tkinter/init.py", line 2017, in init
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: unknown color name "BACKGROUND"

I have compiled Python 36, (after installed base-devel, gcc,) from source then reboot the system and it works.

**Comment by condor2** [comment]
Not an Anarchy bug

**Comment by hamdyaea** [comment]
For python 3.6 a dependence is needed before the installation. In debian it’s python base-devel. Without it I have the same mistake.

**Comment by condor2** [comment]
Ah you mean when install python from programming menu, and not manually install...
